### ISSUE TITLE
Conversion pod fails in restricted namespaces

### ISSUE THREAD

**Issue by ahadas** [kubev2v/forklift#173]
When migrating to a namespace that is labeled with `pod-security.kubernetes.io/enforce=restricted`, the migration fails because the conversion pod cannot start there with the following error:
`pods "..." is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "vddk-side-car", "virt-v2v" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "vddk-side-car", "virt-v2v" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or containers "vddk-side-car", "virt-v2v" must set securityContext.runAsNonRoot=true), seccompProfile (pod or containers "vddk-side-car", "virt-v2v" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`
I'm going to drop that security label from namespaces that are created by our testing framework and this change would need to be reverted when fixing this issue

**Comment by liranr23** [comment]
when having the namespace with the enforced and we do set the security context, fs - 107 (qemu) and seccomp it conflicts:
`pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/populate]: Forbidden: seccomp may not be set,`

`provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{107}: 107 is not an allowed group,`

it will require further investigation.
