### ISSUE TITLE
Updating an existent Provider is stuck in 'Staging' status forever

### ISSUE THREAD

**Issue by polinaag** [kubev2v/forklift#181]
Let's say there is an oVirt Provider correctly defined and used successfully for migration. Then I think the engine was re-deployed. I see in cluster 'Conenction Error' for this provider which is completely ok.
I have got a new certificate for the re-deployed engine and wanted to update the Provider in cluster by Edit Provider UI option with this new certificate (the certificate is correct , tested separately).
The Provider's update looks like stuck forever in 'staging status'.
oc describe Provider rhv-tlv2-05-add returns:
Warning  ConnectionTestFailed     17m (x2 over 17h)  provider  Connection test, failed: GET failed. caused by: 'Get "https://hosted-engine-***/ovirt-engine/sso/oauth/token?grant_type=password&password=***&scope=ovirt-app-api&username=admin%40internal": x509: certificate signed by unknown authority'

Delete and re-create Provider works,  but all the storage/network mappings don't reload the source and we see the mappings with not available sources 
![image](https://user-images.githubusercontent.com/35101331/222231703-313a4a64-c4d2-42dd-8a89-f1555606f5f2.png)

**Comment by mmartinv** [comment]
Updating the `Provider` configuration modifies the `Secret` associated with that `Provider` and, if I am not mistaken, that new `Secret` will take effect only after redeploying the `forklift-controller` (you don't need to recreate the provider). I might be wrong but I think there's nothing we can do about it, it's just like secrets work, they are not remounted in pods using them.

**Comment by yaacov** [comment]
@polinaag hi, I played with #200 and it fixes the providers phase, it did fix the mappings on my env, but I don't know why :-) so I'm not sure it also fixes this issue.

**Comment by sgratch** [comment]
@polinaag @yaacov @mmartinv  the use case I noticed is a bit different, check following screencast:

https://user-images.githubusercontent.com/18169498/223479543-e50600e7-dda3-4c48-bcc9-8fb835581109.mp4

##

Generally, it seems that the `status.conditions` within the provider CR are updated ok, the only problem is that the `status.phase` is change to `Staging` intead of `ConnectionFailed`.

**Comment by polinaag** [comment]
@sgratch @yaacov  Hi Sharon , I tried the screencast use case,but I get Danger alert:Cannot edit provider
admission webhook "secrets.forklift.konveyor" denied the request: Invalid credentials on trying to edit user name

![editprovider](https://user-images.githubusercontent.com/35101331/223694392-49f532cd-1f76-4ffe-b0b7-f71a94b1e146.png)

**Comment by mnecas** [comment]
looks like wrong username `admin@intern` -> `admin@internal`

**Comment by polinaag** [comment]
@mnecas, yes it is by purpose ,i wanted to reproduce screencast use case that Sharon posted

**Comment by mmartinv** [comment]
This is expected, the admission webhook does not allow any updates if the connection fails after testing the new credentials. To test this you will need to change the user's password in ovirt's side.

**Comment by ahadas** [comment]
yep, that's expected in 2.4 that the validation webhook would block it when we have access to ovirt and see that the provided credentials are invalid

**Comment by ahadas** [comment]
@polinaag about the original issue - we have a bigger issue when trying to update the password that is used for connecting to the source provider and that one wasn't prioritized (because this is not a common flow) - that's removing and redefining the provider works for you then this is a low severity issue

**Comment by sgratch** [comment]
> @polinaag @yaacov @mmartinv the use case I noticed is a bit different, check following screencast:
> ...
> Generally, it seems that the status.conditions within the provider CR are updated ok, the only problem is that the status.phase is change to Staging intead of ConnectionFailed.

PR #200 fixed the specific issue mentioned by me with screencast above.

**Comment by jsakil14** [comment]
@ahadas  I am now in a similar staging status - describing provider gives - I dont know what is wrong , this is the kubevirt environment where the operator is installed - what would be wrong here or how I can fix this

```
Name:         host
Namespace:    konveyor-forklift
Labels:       <none>
Annotations:  <none>
API Version:  forklift.konveyor.io/v1beta1
Kind:         Provider
Metadata:
  Creation Timestamp:  2024-07-03T11:35:23Z
  Generation:          1
  Managed Fields:
    API Version:  forklift.konveyor.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .:
          k:{"uid":"REMOVED"}:
      f:spec:
        .:
        f:secret:
        f:type:
        f:url:
    Manager:      OpenAPI-Generator
    Operation:    Update
    Time:         2024-07-03T11:35:23Z
    API Version:  forklift.konveyor.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:observedGeneration:
        f:phase:
    Manager:      forklift-controller
    Operation:    Update
    Subresource:  status
    Time:         2024-07-03T11:36:47Z
  Owner References:
    API Version:     forklift.konveyor.io/v1beta1
    Kind:            ForkliftController
    Name:            forklift-controller
    UID:             REMOVED
  Resource Version:  118477449
  UID:               REMOVED
Spec:
  Secret:
  Type:  openshift
  URL:   
Status:
  Conditions:
    Category:              Required
    Last Transition Time:  2024-07-03T11:35:23Z
    Message:               Connection test, succeeded.
    Reason:                Tested
    Status:                True
    Type:                  ConnectionTestSucceeded
    Category:              Advisory
    Last Transition Time:  2024-07-03T11:35:23Z
    Message:               Validation has been completed.
    Reason:                Completed
    Status:                True
    Type:                  Validated
    Category:              Advisory
    Last Transition Time:  2024-07-03T11:36:47Z
    Message:               Loading the inventory.
    Reason:                Started
    Status:                True
    Type:                  LoadInventory
  Observed Generation:     1
  Phase:                   Staging
Events:
  Type    Reason                   Age                From      Message
  ----    ------                   ----               ----      -------
  Normal  ConnectionTestSucceeded  17m                provider  Connection test, succeeded.
  Normal  Validated                17m                provider  Validation has been completed.
  Normal  LoadInventory            17m                provider  Loading the inventory.
  Normal  LoadInventory            16m (x2 over 16m)  provider  Loading the inventory.
  Normal  LoadInventory            16m (x2 over 16m)  provider  Loading the inventory.

```

**Comment by ahadas** [comment]
@jsakil14 yeah, need to see the log of the inventory container within forklift-controller pod

**Comment by jsakil14** [comment]
I just redeployed the operator and it looks good. Now I am facing a similar issue when trying to add another kubevirt cluster as an openshift type provider , do we have a pre-requisites for service account bearer token like roles and bindings , because I am seeing errors on inventory container about privileges...

**Comment by ahadas** [comment]
@jsakil14 sure, Forklift needs to be able to query things from that provider. @bennyz do we have a list of resources that we need permissions on?

**Comment by bennyz** [comment]
I am not entirely sure what exactly is missing, but I think these two can be used as reference:
https://raw.githubusercontent.com/kubev2v/forklift/a8aeb93bdacc9a28f5879d7eab764fd09ad54d28/operator/config/rbac/api/role.yaml
https://raw.githubusercontent.com/kubev2v/forklift/a8aeb93bdacc9a28f5879d7eab764fd09ad54d28/operator/config/rbac/forklift-controller_role.yaml

Whether something can be dropped depends on the type of migration (for example, kubevirt -> kubevirt requires the virtualmachineexports permissions, but other source don't need this)

**Comment by yaacov** [comment]
docs about permisions:
https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.6/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#rhv-prerequisites_mtv

**Comment by jsakil14** [comment]
> docs about permisions: https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.6/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#rhv-prerequisites_mtv
> 
> EDIT - https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.6/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#non-admin-permissions_cli

Thanks , I created rolebindings following this roles and was successful.

**Comment by jsakil14** [comment]
Are we good to close this issue? Looks like original issue was fixed long back.

**Comment by ahadas** [comment]
I'm not sure whether the original issue was actually fixed but as there is a reasonable workaround (recreating the provider), it's unlikely this issue would be addressed any time soon so yeah, it makes sense to close it
