### ISSUE TITLE
Start PVC-consumer pod with the right virt-v2v image (el8/el9)

### ISSUE THREAD

**Issue by ahadas** [kubev2v/forklift#219]
See #215

**Comment by liranr23** [comment]
we need the consumer on el9 (in the PR, we look for useEl9...).

**Comment by ahadas** [comment]
@liranr23 right, that's no longer an issue after addressing [this](https://github.com/kubev2v/forklift/pull/215#discussion_r1133240039) - it's a bit confusing though because we check `UseEl9VirtV2v` in `EnsureDataVolumes` and then in `createPodToBindPVCs` we use `Settings.Migration.VirtV2vImageCold` - because we know `UseEl9VirtV2v` returns true only for cold-migration to the local cluster.. how about trying to see how to make the code a bit more self-explanatory or at least add a comment that clarifies this in the current code?

**Comment by liranr23** [comment]
added a comment in https://github.com/kubev2v/forklift/pull/242
