### ISSUE TITLE
Creating an OpenStack provider with PIN+Token password will cause the user Token to be locked

### ISSUE THREAD

**Issue by qiyuann** [kubev2v/forklift#269]
Using kerberos ID and PIN+Token as the username and password when creating the OpenStack provider, the provider is created, but the status is "Connection Failed" with description "Connection test, failed: Authentication failed". 
The Token will be locked because of too many failed authentication attempts. The kerberos user can't log into the OpenStack until the Token is unlocked.

If PIN+Token is not supported, it should block provider creation, not to validate the credentials many times.

**Comment by mmartinv** [comment]
The main problem is that PIN+Token is valid only for few seconds. This means that the connection is successful when tested before creating the provider but it will fail right after. There is not much we can do about it. There's a pending PR implementing some additional authentication types (other than username/password). Please take a look at #309.

**Comment by ahadas** [comment]
@mmartinv @qiyuann so can we say that #309 is supposed to close this one?

**Comment by mmartinv** [comment]
Yeah I would say so.
