### ISSUE TITLE
Reconcile in case the snapshot in use in ovirt

### ISSUE THREAD

**Issue by liranr23** [kubev2v/forklift#279]
When creating multiple snapshots, it is possible forklift is too fast and ovirt is still creating the previous snapshot. In that case we hit:
`Fault reason is "Operation Failed". Fault detail is "[Cannot create Snapshot. Snapshot is currently being created for VM golden_env_mixed_virtio_2_1.]". HTTP response code is "409". HTTP response message is "409 Conflict".`

This also may happen when deleting the snapshots. We better reconcile in such case and not fail the whole migration.

**Comment by ahadas** [comment]
It's unlikely that when triggering the snapshot creation (by default every hour) it conflicts with the previous snapshot creation (which is supposed to be almost immediate - as it doesn't include memory). I'm closing this in favor of #283 that provides a broader scope of this issue
