### ISSUE TITLE
 spec.accessModes: Forbidden: may not use ReadWriteOncePod with other access modes

### ISSUE THREAD

**Issue by tekkifygamer** [kubev2v/forklift#316]
Hi there,

I'm currently trying to migrate some VMs over to openshift, and it is failing on the storage migration part.

Error:
        pipeline:
          - description: Initialize migration.
            error:
              phase: Running
              reasons:
                - >-
                  PersistentVolumeClaim "a95f2952-f020-45eb-9d5c-e62cae09fa8e"
                  is invalid: [spec.accessModes: Unsupported value:
                  "ReadWriteOncePod": supported values: "ReadOnlyMany",
                  "ReadWriteMany", "ReadWriteOnce", spec.accessModes: Forbidden:
                  may not use ReadWriteOncePod with other access modes]
                  
Is there an option to manually set the access mode? I'm using the built-in LVM storage operator and it doesn't look like it has RWOP capability.

Thanks

**Comment by ahadas** [comment]
@tekkifygamer did you manage to sort it out?

**Comment by tekkifygamer** [comment]
> @tekkifygamer did you manage to sort it out?

Unfortunately not, still trying to get it to work. If you need more detail I’m happy to provide it but am unsure where to start

**Comment by bennyz** [comment]
> ReadWriteOncePod

Can you share the yaml of the storage class you're using?

**Comment by tekkifygamer** [comment]
> > ReadWriteOncePod
> 
> Can you share the yaml of the storage class you're using?

`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lvms-vg1
  uid: 347a2e34-2e89-4fb4-89ae-03dd6a60715e
  resourceVersion: '23490'
  creationTimestamp: '2023-04-29T00:47:25Z'
  annotations:
    description: Provides RWO and RWOP Filesystem & Block volumes
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: manager
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2023-04-29T00:47:25Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:description': {}
            'f:storageclass.kubernetes.io/is-default-class': {}
        'f:parameters':
          .: {}
          'f:csi.storage.k8s.io/fstype': {}
          'f:topolvm.io/device-class': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: topolvm.io
parameters:
  csi.storage.k8s.io/fstype: xfs
  topolvm.io/device-class: vg1
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer`

**Comment by bennyz** [comment]
According to: https://github.com/kubevirt/containerized-data-importer/blob/c5f767d910bf1c252aba7882dabc57a376594e1d/pkg/storagecapabilities/storagecapabilities.go#L221

It doesn't look incorrect to use RWOP, but it was introduced in k8s 1.22
Which version are you using?

**Comment by tekkifygamer** [comment]
> According to: https://github.com/kubevirt/containerized-data-importer/blob/c5f767d910bf1c252aba7882dabc57a376594e1d/pkg/storagecapabilities/storagecapabilities.go#L221
> 
> It doesn't look incorrect to use RWOP, but it was introduced in k8s 1.22 Which version are you using?

Openshift 4.12.13 hasn't worked, and neither has 4.12.15

**Comment by tekkifygamer** [comment]
> > According to: https://github.com/kubevirt/containerized-data-importer/blob/c5f767d910bf1c252aba7882dabc57a376594e1d/pkg/storagecapabilities/storagecapabilities.go#L221
> > It doesn't look incorrect to use RWOP, but it was introduced in k8s 1.22 Which version are you using?
> 
> Openshift 4.12.13 hasn't worked, and neither has 4.12.15

Thought I'd add some more info:

Migrating from: oVirt 4.5.4 with NFS storage
Migrating to: Openshift Virtualization 4.12.15

**Comment by ahadas** [comment]
> > > According to: https://github.com/kubevirt/containerized-data-importer/blob/c5f767d910bf1c252aba7882dabc57a376594e1d/pkg/storagecapabilities/storagecapabilities.go#L221
> > > It doesn't look incorrect to use RWOP, but it was introduced in k8s 1.22 Which version are you using?
> > 
> > 
> > Openshift 4.12.13 hasn't worked, and neither has 4.12.15
> 
> Thought I'd add some more info:
> 
> Migrating from: oVirt 4.5.4 with NFS storage Migrating to: Openshift Virtualization 4.12.15

@tekkifygamer  is it a warm or cold migration?

**Comment by ahadas** [comment]
> According to: https://github.com/kubevirt/containerized-data-importer/blob/c5f767d910bf1c252aba7882dabc57a376594e1d/pkg/storagecapabilities/storagecapabilities.go#L221
> 
> It doesn't look incorrect to use RWOP, but it was introduced in k8s 1.22 Which version are you using?

@bennyz take a look at [what k8s check when producing this error](https://github.com/kubernetes/kubernetes/blob/4115b2b1803fad5233921b168b46ba346734f228/pkg/apis/core/validation/validation.go#L1721) - it means the PV is set with multiple access modes

**Comment by tekkifygamer** [comment]
> > > > According to: https://github.com/kubevirt/containerized-data-importer/blob/c5f767d910bf1c252aba7882dabc57a376594e1d/pkg/storagecapabilities/storagecapabilities.go#L221
> > > > It doesn't look incorrect to use RWOP, but it was introduced in k8s 1.22 Which version are you using?
> > > 
> > > 
> > > Openshift 4.12.13 hasn't worked, and neither has 4.12.15
> > 
> > 
> > Thought I'd add some more info:
> > Migrating from: oVirt 4.5.4 with NFS storage Migrating to: Openshift Virtualization 4.12.15
> 
> @tekkifygamer is it a warm or cold migration? and do you use MTV 2.4?

Cold migration, MTV 2.4 yep

**Comment by ahadas** [comment]
@tekkifygamer just edited the comment above but I'll repeat here in case you've missed:
Assuming you do cold-migrations using MTV 2.4, you can change accessModes on the StorageProfile - [we currently "take" all the accessModes that are associated with the volumeMode in the storage profile](https://github.com/kubev2v/forklift/blob/main/pkg/controller/plan/kubevirt.go#L803) without taking into account that RWOP conflicts with ReadWriteOnce, ReadOnlyMany and ReadWriteMany

**Comment by tekkifygamer** [comment]
> @tekkifygamer just edited the comment above but I'll repeat here in case you've missed: Assuming you do cold-migrations using MTV 2.4, you can change accessModes on the StorageProfile - [we currently "take" all the accessModes that are associated with the volumeMode in the storage profile](https://github.com/kubev2v/forklift/blob/main/pkg/controller/plan/kubevirt.go#L803) without taking into account that RWOP conflicts with ReadWriteOnce, ReadOnlyMany and ReadWriteMany

Apologies, I'm still a little new to all of this (kubernetes). I edit my storage map, correct? I'm also a little unsure as to what I need to set. I appreciate your help on this issue :)

**Comment by ahadas** [comment]
@tekkifygamer sure, no problem :) you have access to the cluster using the command line? if you do, identify the relevant StorageProfile with `oc get storageprofile`, and then edit it with `oc edit storageprofile <storage-profile-name>` - this will allow you to change the `spec` of the StorageProfile, if it's empty you can replace the `{}` part with, e.g.,
```yaml
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Block
```
and retrigger the migration

**Comment by tekkifygamer** [comment]
> @tekkifygamer sure, most of those who contribute to Forklift/MTV nowadays came from oVirt so we were in the same situation few months ago :) do you have access to the cluster using the command line? if you do, identify the relevant StorageProfile with `oc get storageprofile`, and then edit it with `oc edit storageprofile <storage-profile-name>` - this will allow you to change the `spec` of the StorageProfile, if it's empty you can replace the `{}` part with claimPropertySets, e.g.,
> 
> ```yaml
> spec:
>   claimPropertySets:
>   - accessModes:
>     - ReadWriteMany
>     volumeMode: Block
> ```
> 
> and retrigger the migration

Thank you so much, I will try this tomorrow. I really appreciate your help on this!

**Comment by tekkifygamer** [comment]
> ```yaml
>   - accessModes:
>     - ReadWriteMany
>     volumeMode: Block
> ```

I quickly tried this just now, and I'm having difficulties.. When I try to edit the storageprofile it deletes any sort of modification made to the config. Unsure how I can solve this problem as I'm using the LVM storage operator, and it seems like it creates this storageprofile on its own. Do I need to create a new one?

**Comment by tekkifygamer** [comment]
> > ```yaml
> >   - accessModes:
> >     - ReadWriteMany
> >     volumeMode: Block
> > ```
> 
> I quickly tried this just now, and I'm having difficulties.. When I try to edit the storageprofile it deletes any sort of modification made to the config. Unsure how I can solve this problem as I'm using the LVM storage operator, and it seems like it creates this storageprofile on its own. Do I need to create a new one?

Looks like the access mode desired by MTV is not supported using the LVM storage operator. Unfortunately, I only have one node available for the migration, so I have to use openshift in SNO mode. When installing openshift virt it forces me to install LVM storage which limits my ability to migrate due to the accessModes error. Looks like I'll need to figure out a workaround by either exporting the local storage over NFS or using a different platform. I appreciate all of those who assisted me with this ticket; it really helps when some documentation is sparse or spread across different websites.

**Comment by ahadas** [comment]
@tekkifygamer yeah, if the operator defines the StorageProfile then you'll need to change it somewhere else, otherwise the changes in the StorageProfile would be overridden by the operator. I'm not familiar with the LVM storage operator but I can take a look to see where the configurable part resides.

Anyway, please don't close this issue - we try to find a workaround that could work for you but we should also indeed fix the access-mode that MTV sets in case ReadWriteOncePod exists

**Comment by ahadas** [comment]
@tekkifygamer I've installed the `LVM Storage` operator and the Openshift Virtualization's hyperconverged operator didn't override the changes I've made in the spec of the storage profile "lvms-vg1", this storage profile looks like this now:
```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  creationTimestamp: "2023-05-01T06:59:58Z"
  generation: 3
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    app.kubernetes.io/version: 4.12.3
    cdi.kubevirt.io: ""
  name: lvms-vg1
  ownerReferences:
  - apiVersion: cdi.kubevirt.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: CDI
    name: cdi-kubevirt-hyperconverged
    uid: 81e8cf51-93f3-4741-9960-61b24e901a9c
  resourceVersion: "24599281"
  uid: 569bef79-c50e-4f85-8446-0afa1fd409b2
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Block
status:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Block
  provisioner: topolvm.io
  storageClass: lvms-vg1
```
can you please show the storage profile that you've edited? according to [this](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/storageprofile.md#user-defined-storage-profile), user-defined properties should not be overridden by the ones provided by CDI...

**Comment by bennyz** [comment]
We looked at the CDI code for fetching the access mode from the storage profile[1] and we should probably do the same, and only fetch one combination, the capabilities are already sorted correctly to prefer Block and ReadWriteMany 


[1] https://github.com/kubevirt/containerized-data-importer/blob/b98001422c95ebf54cb41d6bc81faab3f70bd6b1/pkg/controller/datavolume/util.go#LL164C2-L164C2

**Comment by ahadas** [comment]
> > ```yaml
> >   - accessModes:
> >     - ReadWriteMany
> >     volumeMode: Block
> > ```
> 
> I quickly tried this just now, and I'm having difficulties.. When I try to edit the storageprofile it deletes any sort of modification made to the config. Unsure how I can solve this problem as I'm using the LVM storage operator, and it seems like it creates this storageprofile on its own. Do I need to create a new one?

@tekkifygamer it just occurred to us that maybe you edited the 'Status' section rather than the 'Spec' and that's why it's getting overridden?
