### ISSUE TITLE
OpenShift Virtualization as provider type:source to enable OCP > OCP vm migrations

### ISSUE THREAD

**Issue by MichaelMarkieta** [kubev2v/forklift#395]
Hi all, wondering if its possible to have OpenShift Virtualization as a provider source so that I can do OCP > OCP vm migrations. Current paths are: [OpenStack, RH Virtualization, VMware] > [OpenShift Virtualization]

**Comment by ahadas** [comment]
@MichaelMarkieta hi, we're inconsistent about where to file issues at the moment so we have them both here and in Jira and it's hard to identify duplication but anyway I also wanted to point out that we have [an epic we have in Jira for this](https://issues.redhat.com/browse/MTV-571)

**Comment by bennyz** [comment]
Initial support added:
https://github.com/kubev2v/forklift/pull/393
https://github.com/kubev2v/forklift/pull/490
