### ISSUE TITLE
Fix disk size alignment when adding FS overhead

### ISSUE THREAD

**Issue by bennyz** [kubev2v/forklift#397]
Should be similar https://github.com/kubevirt/containerized-data-importer/blob/8ced30251cb1b1641ce70b9a0d574d55f8f43061/pkg/controller/common/util.go#L1274

**Comment by ahadas** [comment]
yeah, it would make sense to do that along with a fix for https://issues.redhat.com/browse/MTV-545

**Comment by bkhizgiy** [comment]
fix for the issue https://github.com/kubev2v/forklift/pull/512
