### ISSUE TITLE
Overview settings dialog, values are changed incorrectly

### ISSUE THREAD

**Issue by nsimsolo** [kubev2v/forklift#457]
some values in settings dialog are changed incorrectly, for example:
After changing "Max concurrent virtual machine migrations" value to 100, the overview shows 50.
This issue is true for the next fields:
- Snapshot pooling interval (seconds)
- Max concurrent virtual machine migrations

[settings_dialog.webm](https://github.com/kubev2v/forklift/assets/25130411/e6b7711c-aa0d-4682-89e6-630ebd9056fa)

**Comment by yaacov** [comment]
moving to UI component: https://github.com/kubev2v/forklift-console-plugin/issues/598
