### ISSUE TITLE
"No boot device" after successfully migrating VM using the default host provider

### ISSUE THREAD

**Issue by prakashmishra1598** [kubev2v/forklift#494]
After completing the migration of a VM using the default host provider created on the target cluster, the migration proceeded to run successfully but after starting up the virtual machine and connecting to it through VNC, the VM wasn't able to boot up with the following error: 
```
Booting from Hard Disk...
Boot failed: not a bootable disk

No bootable device.
```

I also found these lines in the logs which specify that the v2v failed:
```
Failed to determine unit we run in, ignoring: No data available
guestfsd: => inspect_get_distro (0x1e4) took 0.01 secs
libguestfs: trace: v2v: inspect_get_distro = "unknown"
i_root = /dev/sda3
i_type = linux
i_distro = unknown
i_osinfo = unknown
i_arch = x86_64
i_major_version = 5
i_minor_version = 0
i_package_format = unknown
i_package_management = unknown
i_product_name = VMware Photon OS 5.0
i_product_variant = unknown
i_windows_systemroot = 
i_windows_software_hive = 
i_windows_system_hive = 
i_windows_current_control_set = 

virt-v2v: error: inspection could not detect the source guest (or physical machine).

Assuming that you are running virt-v2v/virt-p2v on a source which is supported (and not, for example, a blank dis
k), then this should not happen.

Inspection field ‘i_distro’ was ‘unknown’.
rm -rf -- '/tmp/v2vnbdkit.bcTLgc'
rm -rf -- '/tmp/v2v.tCVBMC'
libguestfs: trace: v2v: close
```

Inspite of this the migration pod runs to completion and the migration is marked as succeeded. Gist of the logs: https://gist.github.com/prakashmishra1598/60e6f814b9fc5014ff3dae020e77303b

**Comment by ahadas** [comment]
yeah, the pod should obviously finish with an error in this situation
about cause of the failure - what type of guest is it?

**Comment by ahadas** [comment]
I can confirm it's a regression on the main branch.
when migrating using 2.4.2 the pod's execution ends with an error:
![2-4-2](https://github.com/kubev2v/forklift/assets/6020068/0feeff0f-abff-4f44-a019-9696a2dc9e76)
when migrating using 'latest' images, the pod's execution ends as 'completed':
![main](https://github.com/kubev2v/forklift/assets/6020068/e59bd412-decb-42f8-9086-75b8a1f227e2)
and when removing [new code that was added recently to the main branch](https://github.com/kubev2v/forklift/blob/main/virt-v2v/cold/entrypoint#L102-L108), the pod's execution ends with an error again:
![main-changed](https://github.com/kubev2v/forklift/assets/6020068/1c9b66f9-c415-48ee-ac83-abde52898021)

**Comment by prakashmishra1598** [comment]
@ahadas This is a linux based PhotonOS guest: https://vmware.github.io/photon/

**Comment by ahadas** [comment]
> @ahadas This is a linux based PhotonOS guest: https://vmware.github.io/photon/

@rwmjones is it supposed to work?

**Comment by ahadas** [comment]
@liranr23 please take a look at https://github.com/kubev2v/forklift/issues/494#issuecomment-1664686693

**Comment by rwmjones** [comment]
I'm fairly sure we had someone try Photon before and it was not supported.  In any case the list of supported guests is here: https://libguestfs.org/virt-v2v-support.1.html (upstream) https://access.redhat.com/articles/1351473 (downstream in RHEL)

**Comment by ahadas** [comment]
@prakashmishra1598 as you notice, we merged a fix for making the pod (and therefore the migration) to fail when the conversion fails but as for the root cause of the failure, if it's important for you to convert Photon guests then it requires a contribution to [virt-v2v](https://github.com/libguestfs/virt-v2v) in order to support that

**Comment by ahadas** [comment]
@prakashmishra1598 @TylerGillson please note that there's [a regression with the action that publishes images from the 'main' branch](https://github.com/kubev2v/forklift/actions/workflows/build-push-images.yml) so the fix is not yet available with 'latest' images - @bennyz looks into it

**Comment by prakashmishra1598** [comment]
Thank you so much for the fix and insights @ahadas @rwmjones 🥳
