### ISSUE TITLE
InvalidVDDKImage Error - how to troubleshoot / fix

### ISSUE THREAD

**Issue by jsakil14** [kubev2v/forklift#971]
This is much needed!! I am struggling to understand what caused this sudden invalidvddkimage error on my vcenter running 7.x and I am using vddk 8.0.2 from broadcom - I queried the controller inventory / main logs - it just tells me InvalidVDDKImage - Steps tried

1. Deleted and recreated vsphere provider with diff. images of vddk - from quay.io/kubevirt/vddk , from broadcom site - vddk 7.03.8.0.2,8.0.3/// 
2. Deleted plans and recreated them
3. Deleted controller pods and updated deployment to have more cpu & mem. resources... below error from provider with - vddk:8.0.2-22388865

<h2 class="co-section-heading " style="padding: 0px; margin: 0px 0px 20px; box-sizing: border-box; font-size: var(--pf-v5-global--FontSize--xl); font-weight: var(--pf-v5-global--FontWeight--normal); font-family: var(--pf-v5-global--FontFamily--heading); line-height: var(--pf-v5-global--LineHeight--md); word-break: break-word; display: flex; justify-content: space-between; color: rgb(255, 255, 255); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box;">Conditions</span></h2>
Type | Status | Updated | Reason | Message

```
--
{"level":"info","ts":"2024-07-24 07:37:30.842","logger":"plan|vvqrj","msg":"Condition added.","plan":{"name":"testmigration1","namespace":"konveyor-forklift"},"condition":{"type":"VDDKInvalid","status":"True","reason":"NotSet","category":"Critical","message":"VDDK init image is invalid","lastTransitionTime":null}}
{"level":"info","ts":"2024-07-24 07:37:30.842","logger":"plan|vvqrj","msg":"Condition deleted.","plan":{"name":"testmigration1","namespace":"konveyor-forklift"},"condition":{"type":"ValidatingVDDK","status":"True","reason":"Started","category":"Advisory","message":"Validating VDDK init image","lastTransitionTime":"2024-07-24T07:32:30Z"}}
{"level":"debug","ts":"2024-07-24 07:37:30.842","logger":"events","msg":"VDDK init image is invalid","type":"Warning","object":{"kind":"Plan","namespace":"konveyor-forklift","name":"testmigration1","uid":"a92ed2c6-1e2f-4725-8b34-306a6ad3e87d","apiVersion":"forklift.konveyor.io/v1beta1","resourceVersion":"136041944"},"reason":"VDDKInvalid"}
{"level":"debug","ts":"2024-07-24 07:37:30.842","logger":"events","msg":"Validating VDDK init image","type":"Normal","object":{"kind":"Plan","namespace":"konveyor-forklift","name":"testmigration1","uid":"a92ed2c6-1e2f-4725-8b34-306a6ad3e87d","apiVersion":"forklift.konveyor.io/v1beta1","resourceVersion":"136041944"},"reason":"ValidatingVDDK"}
{"level":"info","ts":"2024-07-24 07:37:30.851","logger":"plan|vvqrj","msg":"Reconcile ended.","plan":{"name":"testmigration1","namespace":"konveyor-forklift"},"reQ":0}
```
-- | -- | -- | -- | --
TargetNameNotValid | True | Jul 24, 2024, 1:02 PM | NotValid | Target VM name does not comply with DNS1123 RFC, will be automatically changed.
VDDKInvalid | True | Jul 24, 2024, 1:07 PM | NotSet | VDDK init image is invalid

_Originally posted by @jsakil14 in https://github.com/kubev2v/forklift/pull/969#discussion_r1689298428_

**Comment by jonner** [comment]
How did you create the vddk image? Did you follow the directions here? https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.6/html-single/installing_and_using_the_migration_toolkit_for_virtualization/ ?

**Comment by jsakil14** [comment]
Yes exactly the same way step by step 

I simply can't get through beyond invalid vddk error, clueless ...

**Comment by jonner** [comment]
You can take a look at the `vddk-validator-$(PLANNAME)-$(RANDOM)` pod and events associated with it to see if there is any additional information available.

**Comment by jsakil14** [comment]
@jonner  There is no pod getting created as soon as I create a plan - pod gets created after starting the migration I guess.

sharing plan details - Also , for note - am creating the image from MAC - vs code - is it supposed to have issues with symbolic links? Image am using broadcom 8.0.3 ...

```
kd plans.forklift.konveyor.io kubevirt
Name:         kubevirt
Namespace:    konveyor-forklift
Labels:       <none>
Annotations:  populatorLabels: True
API Version:  forklift.konveyor.io/v1beta1
Kind:         Plan
Metadata:
  Creation Timestamp:  2024-07-26T13:20:26Z
  Generation:          1
  Managed Fields:
    API Version:  forklift.konveyor.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:map:
          .:
          f:network:
          f:storage:
        f:provider:
          .:
          f:destination:
          f:source:
        f:targetNamespace:
        f:vms:
    Manager:      Mozilla
    Operation:    Update
    Time:         2024-07-26T13:20:26Z
    API Version:  forklift.konveyor.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:migration:
        f:observedGeneration:
    Manager:         forklift-controller
    Operation:       Update
    Subresource:     status
    Time:            2024-07-26T13:20:49Z
  Resource Version:  138418008
  UID:               0824ee17-96c6-44d0-a5dc-3088c20e98f8
Spec:
  Map:
    Network:
      API Version:  forklift.konveyor.io/v1beta1
      Kind:         NetworkMap
      Name:         localhost-rspxr
      Namespace:    konveyor-forklift
      UID:          567e69c2-e970-4c41-a0bc-36d9ac8eac73
    Storage:
      API Version:  forklift.konveyor.io/v1beta1
      Kind:         StorageMap
      Name:         localhost-gr9fx
      Namespace:    konveyor-forklift
      UID:          724e735a-c1e2-4f1d-a784-c1c937c0a3ac
  Provider:
    Destination:
      API Version:  forklift.konveyor.io/v1beta1
      Kind:         Provider
      Name:         host
      Namespace:    konveyor-forklift
      UID:          60624b33-fe96-423e-b205-750d3b486332
    Source:
      API Version:   forklift.konveyor.io/v1beta1
      Kind:          Provider
      Name:          localhost
      Namespace:     konveyor-forklift
      UID:           2a02d0c6-9df3-419b-b8fb-4d798ae7b4cc
  Target Namespace:  konveyor-forklift
  Vms:
    Id:    vm-7836654
    Name:  test-01-kubevirt
Status:
  Conditions:
    Category:              Critical
    Last Transition Time:  2024-07-26T13:20:49Z
    Message:               VDDK init image is invalid
    Reason:                NotSet
    Status:                True
    Type:                  VDDKInvalid
  Migration:
  Observed Generation:  1
Events:
  Type     Reason          Age                 From  Message
  ----     ------          ----                ----  -------
  Normal   ValidatingVDDK  90s (x2 over 113s)  plan  Validating VDDK init image
  Warning  VDDKInvalid     90s                 plan  VDDK init image is invalid
```

**Comment by camrossi** [comment]
I am also facing the same issue. I tried with 8.0.3 and 8.0.1 (since the instructions are saying to use 8.0.1) and both are failing with the same error and is very unclear what to do/where is the issue. 

Also is not clearly documented what to put as `vddkInitImage` do I put the image stream ? The internal Registry Name? 
I tried with:
`image-registry.openshift-image-registry.svc:5000/openshift-mtv/vddk@sha256:3f536fb1815220447e25430492ea38c3709c2a9c75e597ec5045ce05050f93dc`
`image-registry.openshift-image-registry.svc:5000/openshift-mtv/vddk:8.0.1`

And still same error.

**Comment by jsakil14** [comment]
Image name , is what you build from podman / docker - it can be
quay.io/kubevirt/vddk-init

For my case I redeployed entire operator and all of a sudden it worked.

I also think , we must emphasize the usage of any Linux OS to build the
docker image rather than windows or Mac , just my thoughts..

**Comment by camrossi** [comment]
Thanks @jsakil14 ! Apparently for me access to pull the images is failing and I get a msg="error authorizing context: access denied" not sure why.

Will troubleshoot it later on!

**Comment by camrossi** [comment]
@jsakil14 so in the end my problem is with the internal registry.
Nothing I can do makes the `forklift-controller` able to pull images from there. 

I tried adding an extra  `rolebinding` of type `system:image-puller` as well as enabling the `imageStream` `lookupPolicy` but nothing I can do solves the fact that the internal registry will just access deny the `forklift-controller` access to the image I have built. 

So I just put the image on `quay.io` on a public repo and now all works. 

The Validation seceded with both 8.0.1 and 8.0.3 (didn't try 8.0.2)

I think we should have some instruction on how to build this in-cluster and how to give access to forklift to it but is probably not for this git issue.

**Comment by jonner** [comment]
When you create a new plan for a provider that specifies a vddk init image, it should spawn a job to validate that vddk image immediately after creation with a name like `vddk-validator-$PLANNAME`. This job will create an associated pod named `$JOBNAME-$RANDOM` which tries to pull the vddk image and verify that it contains the expected files. If the image fails to be pulled, it will retry a couple times until the job fails (typically after 300 seconds) at which point the pod will apparently be deleted. So you may only be able to see the pod and view the events related to that pod while the validation is running.

**Comment by jsakil14** [comment]
https://github.com/kubev2v/forklift/issues/971#issuecomment-2258490414
